### ISSUE TITLE
[N5][devel:1344] app orientation

### ISSUE THREAD

**Issue by Aurze** [ubports/unity8#266] opened 2020-01-22 21:46 UTC
In convergence, when you snap a window (ex: browser) to take half the screen it get a ratio higher than larger and the browser orientation switch and endup side-way.

**Comment by UniversalSuperBox** [comment] 2021-05-10 22:03
This is a duplicate of https://github.com/ubports/ubuntu-touch/issues/1344, which was fixed by https://github.com/ubports/morph-browser/pull/430

**Closed as completed by UniversalSuperBox** 2021-05-10 22:03 UTC
