### ISSUE TITLE
Indicator menue: Items got desynced from selection logic

### ISSUE THREAD

**Issue by Flohack74** [ubports/unity8#201] opened 2019-10-01 17:42 UTC
I somehow managed to get selected indicator desynced with the white selection bar:
![grafik](https://user-images.githubusercontent.com/16186470/65986087-78337e00-e483-11e9-9412-127f00e9a841.png)
On the top you can see that Notifications is selected on the left, where the white bar is on the rightmost indicator. Also there is no content now.

**Comment by UniversalSuperBox** [comment] 2021-05-10 23:30
Duplicate of https://github.com/ubports/unity8/issues/132 and https://github.com/ubports/unity8/issues/132

**Closed as completed by UniversalSuperBox** 2021-05-10 23:30 UTC
Labels: bug, edge

**Comment by Flohack74** [comment] 2021-05-11 10:51
U sure its a duplicate of 2x the same ticket no? =)
