### ISSUE TITLE
Confusing Animation When Pulling down Indicator

### ISSUE THREAD

**Issue by cibersheep** [ubports/unity8#132] opened 2019-04-22 04:15 UTC
Pull from the indicator bar from Notifications is kind of ok, but pulling it from for example Sound or Battery indicators creates a weird animation that is confusing.

**Comment by NeoTheThird** [comment] 2019-05-17 12:23
What do you mean exactly? I don't see anything weird going on.

**Comment by cibersheep** [comment] 2019-05-17 13:28
It might be a N5 thing but if you pull from, let's say, the clock on non edge channels, the drop down is smooth and keep focus on the clock. If you do on edge channel the animation of the panel goes a bit crazy for a moment and then focus is a bit lost.

Can I forward mir to record the screen to the computer somehow? That would make more sense

**Comment by NeoTheThird** [comment] 2019-05-18 10:04
http://docs.ubports.com/en/latest/userguide/advanceduse/screencasting.html

**Comment by cibersheep** [comment] 2019-05-28 18:11
Pulling down from wifi indicator (good animation)
https://youtu.be/FYzrf6QjlNs

Pulling from audio indicator (confusing animation)
https://youtu.be/pWSDqM2NETc

**Comment by cibersheep** [comment] 2019-05-28 18:18
I'm testing this on N5 (on landscape is more obvious).
Recently got an E5 on edge as well. Animation looks correct on E5 edge

**Comment by mariogrip** [comment] 2019-06-29 15:31
Can you check if this is fixed by: https://github.com/ubports/unity8/pull/158?

**Comment by cibersheep** [comment] 2019-06-29 20:13
Ouh! Thanks @mariogrip I can test tomorrow / Monday

**Comment by cibersheep** [comment] 2019-07-01 20:10
Tested on N5 with latest updates and it's not fixed yet.
- Pulling from Notifications, GPS (if visible), Bluetooth (if visible), Network and time indicators works ok
- Pulling from Sound or battery creates this weird animation

If all this indicators are visible: 
- pulling from sound works fine
- Battery creates weird animation

![imatge](https://user-images.githubusercontent.com/6640041/60463631-cc448180-9c4c-11e9-95da-3166fbf124ff.png)

**Comment by cibersheep** [comment] 2019-07-02 10:48
I have tested on E5 and works good. It looks to be a specific thing for N5?

**Comment by UniversalSuperBox** [comment] 2019-08-03 03:47
Maybe it's related to screen size. I see it less on the Oneplus One than the FP2 or Nexus 5, but it still happens.

I wonder if we have a race condition in a couple of bindings. What appears to happen is the indicator you dragged from opens normally, but the indicator bar opens with its middle on a different one. For example, I pull down Notifications but its middle appears to be on Location. If you release fast enough, this normally isn't a problem. The indicator bar scrolls back to where you are when the animations settle. However, if you are still holding the handle, you switch to the indicator directly above where your finger is. In my hypothetical case, I opened Notifications and then Location becomes focused when I move.

**Comment by UniversalSuperBox** [comment] 2020-01-16 01:48
This has been difficult to reproduce because it's related to the number of indicators you have open at any time.

A better method to reproduce:

Use a Nexus 5 or Fairphone 2 for best effect.

1. Remove your SIM card, if inserted
1. Disable Bluetooth, if enabled
1. Disable location, if enabled
1. Open notifications indicator
1. Close indicators
1. Press on the Date indicator. Do not drag down.

You should notice that instead of the Date indicator, the System indicator is open.

Repeating this action may improve or worsen the behavior. It seems random at best.

This appears to be related to the expansion of hidden indicators. The more indicators to expand, the more pronounced the problem.

**Closed as completed** 2020-02-24 16:28 UTC
Labels: bug

**Comment by jonnius** [comment] 2020-03-16 20:10
No confusing animation here on my FP2 with RC.

**Comment by Danfro** [comment] 2020-03-17 04:55
Looking fine on E5, RC.

**Comment by cibersheep** [comment] 2020-03-17 22:30
N5 RC, animation is excellent :)

**Comment by j2g2rp** [comment] 2020-03-17 22:46
Works correctly on M10FHD

**Comment by luksus42** [comment] 2020-03-18 19:48
Great on E4.5 on RC.
