### ISSUE TITLE
Cannot load desktop in bionic

### ISSUE THREAD

**Issue by luispabon** [ubports/unity8#37] opened 2018-05-10 15:02 UTC
Upon successful login, I get kicked back to lightdm:

```
May 10 15:56:35 luis-XPS-15-9560 systemd[1]: Stopping Session c10 of user unity8.
May 10 15:56:35 luis-XPS-15-9560 systemd[1]: Stopped Session c10 of user unity8.
May 10 15:56:35 luis-XPS-15-9560 unity8-session[27942]: [2018-05-10:15:56:35.104] qtmir.screens: ScreensModel::ScreensModel
May 10 15:56:35 luis-XPS-15-9560 unity8-session[27942]: [2018-05-10:15:56:35.104] QSocketNotifier: Can only be used with threads started with QThread
May 10 15:56:35 luis-XPS-15-9560 unity8[28010]: cannot open display: 
May 10 15:56:35 luis-XPS-15-9560 unity8-session[27942]: /usr/bin/unity8-session: line 75: [: !=: unary operator expected
May 10 15:56:35 luis-XPS-15-9560 unity8-session[27942]: /usr/bin/unity8-session: line 79: kill: (28010) - No such process
May 10 15:56:36 luis-XPS-15-9560 lightdm[28225]: pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "unity8"
```

**Comment by pixelr0** [comment] 2018-05-25 05:13
https://github.com/ubports/unity8-desktop-install-tools/issues/22

**Comment by Flohack74** [comment] 2018-05-25 09:46
duplicate of ubports/unity8-desktop-install-tools#22

**Closed as completed by Flohack74** 2018-05-25 09:46 UTC
Labels: duplicate
