### ISSUE TITLE
Installing Unity8 onto Ubuntu 18.04 adds/changes indicators for Unity7

### ISSUE THREAD

**Issue by GizmoChicken** [ubports/unity8#51] opened 2018-07-21 00:43 UTC
I previously installed Unity7 (using the [ubuntu-unity-desktop](https://packages.ubuntu.com/bionic/ubuntu-unity-desktop) meta-package from the Universe repo) onto Ubuntu 18.04 LTS (64-bit) and selected LightDM as default.  All works as expected.

However, installing Unity8 (from the UBports repo) onto the above described system adds/changes indicators for Unity7.   See attached screenshots.  

Unity7 indicators _before_ installing Unity8:
![unity7 indicators before unity8 installation](https://user-images.githubusercontent.com/9044094/43029964-1d9f436c-8c59-11e8-8572-bad066407021.png)

Unity7 indicators _after_ installing Unity8:
![unity7 indicators after unity8 installation](https://user-images.githubusercontent.com/9044094/43029977-458892fc-8c59-11e8-9f4a-69b2041e122e.png)

Note that the added (network) indicator is redundant, and the changed (power) indicator remains functional.

As an aside, I'm currently testing Unity8 on a non-production test system.  So from my perspective, this bug isn't a high priority.  But I expect that installing Unity8 alongside Unity7 will, eventually, become a common use case.  Indeed, I hope that one day we'll see an "Ubuntu Unity" flavor that ships with _both_ Unity7 and Unity8, hopefully with Unity8 as the default DE, and with Unity7 as a fallback DE for pure Xorg sessions.

System:
Processor: Intel Core i5-6200U
Graphics: Intel HD Graphics 520
Distro: Ubuntu 18.04 LTS (64-bit) onto which Unity7 (ubuntu-unity-desktop from the Universe repo), Unity8 (from the UBports repo), and Mir 0.32.1 (from ppa:mir-team/release) are installed.

**Comment by dobey** [comment] 2018-09-30 13:47
It seems there is no label for 'regression' but this is one, as the indicator-network starting under unity7 issue was fixed prior to Canonical dropping the projects. There seems to be some lost changes that were definitely in various projects prior to that point, but which seem to not exist in the ubports builds. This is one of those.

**Comment by dobey** [comment] 2018-10-01 02:16
OK. The indicator-network issue is fixed now, and it should not start under sessions other than unity8. As for the battery icon, it looks like ubuntu-mono-{light,dark} themes are not using the correct icon names, and the fallbacks from Humanity-Dark are being picked up instead. Looking at the indicator-power code there doesn't seem to be any recent changes that should cause this, though, so I'm not sure why that happened exactly. Anyway, I'm closing this as the main issue is fixed. Please open another issue on indicator-power itself, if you wish to discuss/debug that particular oddity any further. Thanks.

**Closed as completed by dobey** 2018-10-01 02:17 UTC
