### ISSUE TITLE
Unity8 testing on Debian

### ISSUE THREAD

**Issue by ConLenov** [ubports/unity8#272] opened 2020-02-10 10:43 UTC
Is it possible to test unity8 on Debian Sid?

**Comment by UniversalSuperBox** [comment] 2020-03-07 17:46
Hi @ConLenov,

Packaging Lomiri for Debian is currently in progress. You can follow the progress at [Sunweaver's blog](https://sunweavers.net/blog/blog/1).

Because this report is a question and not a bug, I'll close it. Thanks for your report!

**Closed as completed by UniversalSuperBox** 2020-03-07 17:46 UTC
